### ISSUE TITLE
Shifting files to the submissions folder

### ISSUE THREAD

**Issue by jeffboichuk** [GCOM7140/r4ds-exercises#8]
@Drasztalos and @JustinLago –

I hope you're well. Just a quick note to share that your files for the R4DS Data Transformation Exercises ([here](https://github.com/GCOM7140/r4ds-exercises/blob/master/01_r4ds-data-transformation-dra9z.R) and [here](https://github.com/GCOM7140/r4ds-exercises/blob/master/01_r4ds-data-transformation-jl7dy.R)) need to be removed or saved within the [submissions folder](https://github.com/GCOM7140/r4ds-exercises/tree/master/submissions). Please come into my office hours today between 1 and 3 pm if you need help shifting these files over or removing them. The steps to shift them include moving your file, committing the change, and pushing the change to GitHub.

Thanks!

**Comment by JustinLago** [comment]
I was able to remove the file and save my hw to the submission folder. Thank you for letting me know!
